### ISSUE TITLE
Create a file

### ISSUE THREAD

**Issue by Matt-Brigida** [Jabettig/Initial-analysis.R#1]
Can you create a file in this repo?  You can put anything in the file, "test" for example.

You then `git add [file name]` to stage the file, `git commit -m "[commit message]"` to commit it, and `git push origin master` to push it to origin (github).

**Comment by Jabettig** [comment]
I added a file to the repository, can you see it’s sufficient to make a pull request on?

Best Regards,
Jacques Anthony Bettig

**Comment by Matt-Brigida** [comment]
Submitted pull request
